spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goat_cloud_test
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
